dist: trusty
language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: caay2000-github
    token:
      secure: "kGOQkh+SqHDmxCjQVy4MsbrYVjXeDLhdHhK60HpbC4QX2eff1n6fA8XLnYlKnhHvihAZaKEowmwbkLlx5KsYv+pXZjXyCFD8lwdLc1OWFCGKezZHDJucDUtifGzvL5YqCE0kSAF97eTG5EsBHnKkJ6zOLwZHWI5gdM/kce4jOPpPdHSp5pJS24cd7frkYq32NBV2Thoy5MuQvr85/e26x+tEWKdAAUm2klF2M5qOnYOqkwIfbkISdU5bAhxLVRMihni5l5z9WjVYjCZgB04JsqRT4a3OWY3jHpmci+pocg+God+Sk7PUR2NFdP+iCXUOFb2mkj46tSCzhxeSkcNTpsmgBa3c6CtIw9k2qCcvWKKpJCzhTQHBoX8HgAOrU0tsqXHmVemaL9yFDVddmrs8MQa7+xKVKSDwmZFYnjV9WKVo+3rQ8TewrWDKlmR/BHRfR+zktZl2+h9m5dfFEel23hidlSjj1YiepTI/ZRmUtQmGdBRWZU5fJjjl8iXe/nlS7Xkl6Avpgvyk0liW6ND2+HBItnTVX0oskV7Isnz1SU/aciCuIKu7QDO60Nytgo8vPn8CoAvsDcNw/3jixeHVmefzXqK2/DWqfgtPYcYQKbycxsPjokbWeRgA4LwnP821DfgUCBFzXOZIoyxgU9DvFJH6cl83ibOiK9YBVax+YGo="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=caay2000_trains-gdx